-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    "user_Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "Username" character varying(20)[] NOT NULL,
    "Password" character varying(20) NOT NULL,
    PRIMARY KEY ("user_Id")
);

COMMENT ON TABLE public.users
    IS 'Table for Users';

CREATE TABLE IF NOT EXISTS public.cards
(
    card_id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    "Name" character varying NOT NULL,
    "Damage" real NOT NULL,
    PRIMARY KEY (card_id)
);

COMMENT ON TABLE public.cards
    IS 'All avaiable Cards in the Game';

CREATE TABLE IF NOT EXISTS public.users_cards
(
    card_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (card_id, user_id)
);

COMMENT ON TABLE public.users_cards
    IS 'Connection between User and Cards. Maps all cards a user has';

ALTER TABLE IF EXISTS public.users_cards
    ADD FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.users_cards
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users ("user_Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;